language: go

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install curl
  - go get -u github.com/laher/goxc

script:
  - cd kokonet-cni
  - go get .
  - go build
  - mkdir -p ${TRAVIS_BUILD_DIR}/dist
  - goxc -d=${TRAVIS_BUILD_DIR}/dist -bc=linux -tasks=clean-destination,xc,archive,rmbin

after_success:
  # put build tgz to bintray
  - curl -T ${TRAVIS_BUILD_DIR}/dist/snapshot/kokonet-cni_linux_amd64.tar.gz -u${BINTRAY_USER}:${BINTRAY_APIKEY} https://api.bintray.com/content/s1061123/generic/kokonet/snapshot-${TRAVIS_COMMIT}/kokonet-cni_linux_amd64-${TRAVIS_COMMIT}.tar.gz
  # publish uploaded file
  - curl -X POST -u${BINTRAY_USER}:${BINTRAY_APIKEY} https://api.bintray.com/content/${BINTRAY_USER}/generic/kokonet/snapshot-${TRAVIS_COMMIT}/publish
  # put it in bintray download list
  - sleep 10 && curl -X PUT -H "Accept: application/json" -H "Content-type: application/json" -u${BINTRAY_USER}:${BINTRAY_APIKEY} https://api.bintray.com/file_metadata/${BINTRAY_USER}/generic/snapshot-${TRAVIS_COMMIT}/kokonet-cni_linux_amd64-${TRAVIS_COMMIT}.tar.gz -d '{"list_in_downloads":true}'
